name: "Check and build all packages"
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build-x86_64:
    name: Build for x86_64-linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check --all-systems
      - run: nix build .
  build-aarch64:
    name: Build for aarch64-linux
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - run: nix build .
